### ISSUE TITLE
Training the set

### ISSUE THREAD

**Issue by kromy** [mittalgovind/fifty#1]
Greetings all

Thank you for your effort in file fragments classification

i'm trying to use the tools "i'm using windows", but i could't run the train command.

can you please give me an example to test the tool?

if you could show me and example for 

fifty train [-d DATA_DIR] [-a ALGO] [-g GPUS] [-p PERCENT] [-n MAX_EVALS] [--down SCALE_DOWN] [--up]  

and 

fifty whatis <input> [-r] [-b BLOCK_SIZE] [-s SCENARIO] [--block-wise] [-o OUTPUT] [-f] [-l] [-v] [-vv] [-vvv] [-m MODEL_NAME]

thanks

**Comment by mittalgovind** [comment]
Hi Kromy, 

Thanks for your interest in using the tool. 

Sure. The following commands might be useful:

`fifty whatis tiff-images -s 4 -b 512` = runs the fourth scenario of fifty on the whole folder of tiff-images considering block sizes of 512 bytes.

For training on a subset of the filetypes, create a txt file with each line comprising of the required filetypes (at separate lines) and give the path to --down option.

You might also find the running `fifty -h` useful. Any further clarifications and doubts are welcome.

**Comment by kromy** [comment]
I appreciate your fast respond, 

I have few questions
1- is it possible to have a fully documented source code if exist to understand it?
2- if i want to train a data set from FFT , how i do it? i tried # fifty train --down train.npz , i tried also fifty train --down dummayfile.txt
3- does the output {OTH: 100} means other than the files types in senario 4?
4- how can solve the issue of TypeError : expected str, bytes  or os.pathlike object, not NoneType ? this is related to number 2 question.

thanks

**Comment by mittalgovind** [comment]
Hi Kromy, 

Sorry for a delayed response.
1- is it possible to have a fully documented source code if exist to understand it?
Ans - Yes, I will can make the code more documented, but also would a flow chart be a better solution to help you understand?

2- if i want to train a data set from FFT , how i do it? i tried # fifty train --down train.npz , i tried also fifty train --down dummayfile.txt
Ans. 
1> You need to download the [FFT-75 dataset ](https://ieee-dataport.org/open-access/file-fragment-type-fft-75-dataset). 
2> Do go through the documentation attached to that page. 
3> To sub-select filetypes only download the first (most generic) scenario. You can generate other scenarios training data (atleast a smaller version) using the first scenarios dataset.
4> When you download the 4k_1.tar.gz or 512_1.tar.gz, extract it to a folder (say, data) and pass the path to this folder only. _Example_: 

> fifty train --data_dir /Users/<username>/Downloads/data --down [scale_down.txt](https://github.com/mittalgovind/fifty/files/3773295/scale_down.txt)

Again, to make myself clear - the full path to the extracted folder from tar file should be saved inside a folder and that folder should be passed (eg, for the above case - /Users/<username>/Downloads/data/4k_1/train.npz)

5> Fifty should have created a dataset for it in the output directory. [If you don't see this, then training would fail.]
6> The training will now start automatically on this dataset [please refer the training options to control this further] and save the best optimized model for your case in the output folder.
7> Pass this model next time you run fifty on your test files. 


3- does the output {OTH: 100} means other than the files types in scenario 4?
Ans. It means that the file is that the classifier is very sure that the file is not one of the other classes (in this case, photo or video formats).  

4- how can solve the issue of TypeError : expected str, bytes or os.pathlike object, not NoneType ? this is related to number 2 question.
4> Need the full error log for exact answer.

Any further clarifications are welcome.

**Comment by kromy** [comment]
thanks a lot 

i'll try to train according to your steps

regarding the documentation source code, i already read your paper "FiFTy: Large-scale File Fragment Type Identification using Neural Networks"

Actually i am doing research about CNN and file classification and i was amazed by your work, i am a beginner in AI and NN, but i took short course about Keras. but i found some difficulties understanding the code. If you have any resources that may help, please drop it here.

Thanks.

**Comment by mittalgovind** [comment]
Hi Kromy, 

Thanks for your interest in our work. I am also a preliminary researcher in this field. Learning like you, everyday. Today I found that [this](https://metacademy.org) site is pretty useful. Have a fun journey.

Regards,
Govind
