### ISSUE TITLE
Question about the order of the code here

### ISSUE THREAD

**Issue by ahmed-masud** [mittalgovind/fifty#4]
https://github.com/mittalgovind/fifty/blob/9aaf00a38ae9b98be8b89ccff8a87082e04054cc/fifty/commands/whatis.py#L181

Is the remapping of the distribution of probabilities to the top 4 types here a bug?

```
            top_labels = df['Class Label'].value_counts()[:4]
            top_labels *= 100 / top_labels.sum()
```

That is to say, is this code supposed to be like this:

```
            top_labels = df['Class Label'].value_counts()
            top_labels *= 100 / top_labels.sum()
            top_labels = top_labels[:4]
```

Or is this intentional?

**Comment by mittalgovind** [comment]
@ahmed-masud Thank you for noticing it. I have fixed it.
